# Generated by Django 3.0.5 on 2020-04-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
