# Generated by Django 3.0.5 on 2020-04-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='librarycategory',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
